AWSTemplateFormatVersion: 2010-09-09
Description: Example Template which will deploy Route Tables for Hub Spoke VPC Subnets
Resources: 
  HubPublicRouteTB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  !ImportValue HubVPCID
      Tags:
      - Key: Name
        Value: HubPublicRouteTable
  HubPrivateRouteTB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  !ImportValue HubVPCID
      Tags:
      - Key: Name
        Value: HubPrivateRouteTable
  SpokePublicRouteTB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  !ImportValue SpokeVPCID
      Tags:
      - Key: Name
        Value: SpokePublicRouteTable
  SpokePrivateRouteTB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  !ImportValue SpokeVPCID
      Tags:
      - Key: Name
        Value: SpokePrivateRouteTable
Outputs:
    HubPublicRouteTBID: 
        Description: Hub Public Route Table 
        Value: !Ref HubPublicRouteTB # Logical ID/Name of Route Table is passed so Route Table id is returned to Value parameter
        Export:
            Name: HubPublicRouteTBID
    HubPrivateRouteTBID: 
        Description: Hub Public Route Table 
        Value: !Ref HubPrivateRouteTB
        Export:
            Name: HubPrivateRouteTBID
    SpokePublicRouteTBID: 
        Description: Hub Public Route Table 
        Value: !Ref SpokePublicRouteTB # Logical ID/Name of Route Table is passed so Route Table id is returned to Value parameter
        Export:
            Name: SpokePublicRouteTBID
    SpokePrivateRouteTBID: 
        Description: Hub Public Route Table 
        Value: !Ref SpokePrivateRouteTB # Logical ID/Name of Route Table is passed so Route Table id is returned to Value parameter
        Export:
            Name: SpokePrivateRouteTBID