AWSTemplateFormatVersion: 2010-09-09
Description: Example Templates that will deploy two VPCS with Internet Gateway, NAT Gatway. (Entire Network Stack)
Resources: # Declare What cloudfromation need to be provision one of the compolosory thing
  HubVPC: # This the Resource Name used in the temp
    Type: AWS::EC2::VPC # Resource Type. Refer Template Reference -> Resource and Property Reference to define this https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html
    Properties:
      CidrBlock: 172.16.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: HubVPC # Array is Key Value Pair
  HubVPCPublicSubnet: 
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref HubVPC   # Using Ref Intrinsic Function Refer previously created HubVPC using Resource name above 
      CidrBlock: 172.16.0.0/24
      AvailabilityZoneId: apse2-az1
      Tags:
         - Key: Name
           Value: HubPublic
    DependsOn: HubVPC
  HubVPCPrivateSubnet: 
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref HubVPC
      CidrBlock: 172.16.1.0/24
      AvailabilityZoneId: apse2-az1 #Specify the Zone ID not the Zone name here
      Tags:
         - Key: Name
           Value: HubPrivate
    DependsOn: HubVPC
  SpokeVPC:
    Type: AWS::EC2::VPC # Resource Type. Refer Template Reference -> Resource and Property Reference to define this https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html
    Properties:
      CidrBlock: 192.168.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: SpokeVPC
  SpokeVPCPublicSubnet: 
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SpokeVPC   # Using Ref Intrinsic Function Refer previously created HubVPC using Resource name above 
      CidrBlock: 192.168.0.0/24
      AvailabilityZoneId: apse2-az1
      Tags:
         - Key: Name
           Value: SpokePublic
    DependsOn: SpokeVPC
  SpokeVPCPrivateSubnet: 
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SpokeVPC   # Using Ref Intrinsic Function Refer previously created HubVPC using Resource name above 
      CidrBlock: 192.168.1.0/24
      AvailabilityZoneId: apse2-az1
      Tags:
         - Key: Name
           Value: SpokePrivate
    DependsOn: SpokeVPC
  HubVPCPublicSubnetRTAssociation: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !ImportValue HubPublicRouteTBID # Import the Route Table Value from Route Table stack Template
      SubnetId: !Ref HubVPCPublicSubnet
    DependsOn: HubVPCPublicSubnet
  HubVPCPrivateSubnetRTAssociation: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !ImportValue HubPrivateRouteTBID # Import the Route Table Value from Route Table stack Template
      SubnetId: !Ref HubVPCPrivateSubnet
    DependsOn:  HubVPCPrivateSubnet
  SpokeVPCPublicSubnetRTAssociation: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !ImportValue SpokePublicRouteTBID # Import the Route Table Value from Route Table stack Template
      SubnetId: !Ref SpokeVPCPublicSubnet
    DependsOn: SpokeVPCPublicSubnet
  SpokeVPCPrivateSubnetRTAssociation: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !ImportValue SpokePrivateRouteTBID # Import the Route Table Value from Route Table stack Template
      SubnetId: !Ref SpokeVPCPrivateSubnet
    DependsOn: SpokeVPCPrivateSubnet
  HubtoSpokePeering: # Peering Creation Logical Name
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      #PeerOwnerId: String This Account ID Used when Cross Account 
      #PeerRegion: String  This required when do cross region Peering
      #PeerRoleArn: String Required when do cross region peering
      VpcId: !Ref HubVPC
      PeerVpcId: !Ref SpokeVPC
      Tags: 
        - Key: Name
          Value: hub-to-spoke-peering
  HubInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: Hub_IGW
  SpokeInternetGateway: 
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: Spoke_IGW
  HubInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment # Have to use this Resource Type in order to  Attach Internet Gateway
    Properties:
      InternetGatewayId: !Ref HubInternetGateway
      VpcId: !Ref HubVPC
  SpokeInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment # Have to use this Resource Type in order to  Attach Interntet Gateway
    Properties:
      InternetGatewayId: !Ref SpokeInternetGateway
      VpcId: !Ref SpokeVPC
  HubNGWIP: 
    Type: AWS::EC2::EIP # Elastic IP creation
    Properties:
      Domain: vpc
  SpokeNGWIP: 
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  HubNATGateway:
   Type: AWS::EC2::NatGateway
   Properties:
      AllocationId: !GetAtt HubNGWIP.AllocationId # Elastic IP has return value called allocation ID. Using GetAtt function Get Allocation ID and specify here 
      SubnetId: !Ref HubVPCPublicSubnet
      Tags:
      - Key: Name
        Value: HubNATGateway
  SpokeNATGateway:
   Type: AWS::EC2::NatGateway
   Properties:
      AllocationId: !GetAtt SpokeNGWIP.AllocationId
      SubnetId: !Ref SpokeVPCPublicSubnet
      Tags:
      - Key: Name
        Value: SpokeNATGateway
  
  
Outputs:
        HubVPCID: # Output Logical ID 
          Description: Hub VPC ID
          Value: !Ref HubVPC  # Logical ID/Name of the HubVPC passed to Ref function so VPC ID is returned
          Export: 
              Name: HubVPCID # Name of the Output Value. This name should be used with ImporValue function
        SpokeVPCID: 
          Description: Spoke VPC ID
          Value: !Ref SpokeVPC 
          Export: 
              Name: SpokeVPCID
        HubIGWID: 
          Description: Hub VPC Internet Gateway ID
          Value: !Ref HubInternetGateway
          Export: 
              Name: HubIGWID
        HubNGWID: 
          Description: Hub VPC NAT Gateway ID
          Value: !Ref HubNATGateway
          Export: 
              Name: HubNGWID
        SpokeIGWID: 
          Description: Spoke VPC Internet Gateway ID
          Value: !Ref SpokeInternetGateway
          Export: 
              Name: SpokeIGWID 
        SpokeNGWID: 
          Description: Spoke VPC Internet Gateway ID
          Value: !Ref SpokeNATGateway
          Export: 
              Name: SpokeNGWID 
        HubToSpokePeeringID: 
          Description: Hub to Spoke Peering ID
          Value: !Ref HubtoSpokePeering
          Export: 
              Name: HubToSpokePeeringID
        
      
